services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser

    ports:
      - "127.0.0.1:8081:80"

    volumes:
      - /srv/storage:/srv
      - /srv/appdata/filebrowser/database:/database
      - /srv/appdata/filebrowser/config:/config

    restart: unless-stopped
