services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser

    ports:
      - "127.0.0.1:8081:80"

    environment:
    - FB_DATABASE=/database/filebrowser.db 

    volumes:
      - /srv/storage:/srv
      - /srv/appdata/filebrowser/database:/database
      - /srv/appdata/filebrowser/config:/config
      - /srv/media/books/staging/manual-import:/srv/books/manual-import
      - /srv/media/downloads/watch:/srv/torrent-watch

    restart: unless-stopped
