---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Jellyfin:
        href: http://whalesea:8096
        description: Media server

    - Sonarr:
        href: http://whalesea:8989
        description: TV automation

    - Radarr:
        href: http://whalesea:7878
        description: Movie automation

    - Prowlarr:
        href: http://whalesea:9696
        description: Indexer manager

- Downloads:
    - qBittorrent:
        href: http://whalesea:8080
        description: Torrent client (VPN-only)

- Network:
    - Gluetun:
        href: http://whalesea:8000
        description: VPN container dashboard (if enabled)
