---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Jellyfin:
        href: http://whalesea:8096
        server: my-docker
        description: Media server
        container: jellyfin
        widget: 
          type:
          url:
          key:

    - Sonarr:
        href: http://whalesea:8989
        server: my-docker
        description: TV automation
        container: sonarr
        widget: 
          type: sonarr 
          url: http://sonarr:8989
          key: 29e0ad18c78f4126a4f0055ee71d55df

    - Radarr:
        href: http://whalesea:7878
        server: my-docker
        description: Movie automation
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: 6486f3c902884e8e9ba33c4a13e5eec0

    - Prowlarr:
        href: http://whalesea:9696
        server: my-docker
        description: Indexer manager
        container: prowlarr
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: adbf53f2ffe84cfca2facab03f0f5f28

- Downloads:
    - qBittorrent:
        href: http://whalesea:8080
        server: my-docker
        description: Torrent client (VPN-only)
        container: gluetun 
        widget:
          type: qbittorrent 
          url: http://192.168.86.144:8080
          username: admin
          password: sL7pe4fp!
    - SABnzbd:
        href: http://192.168.x.x:8085
        description: Usenet downloader
        server: my-docker
        container: sabnzbd
        widget:
          type: sabnzbd
          url: http://192.168.86.144:8085
          key: 79990e4cfa904279afcf5f04f8e95b1c

- Network:
    - Gluetun:
        href: http://whalesea:8000
        server: my-docker
        description: VPN container dashboard (if enabled)
        container: gluetun
        widget:
          type:
          url:
          key:


- Infrastructure:
    - Homepage:
        href: http://whalesea:3000
        description: Dashboard
        server: my-docker
        container: homepage
