---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- system:
    title: Server
    host: whalesea

- datetime:
    format:
      timeStyle: short
      dateStyle: medium
