services:
  
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    restart: unless-stopped
    networks:
      - media-net
    volumes:
      - /srv/appdata/apprise/apprise.yml:/config/apprise.yml

networks:
  media-net:
    external: true
