services:
  openbooks:
    image: evanbuss/openbooks:latest
    container_name: openbooks
    restart: unless-stopped
    ports:
      - "8083:8080"
    command: ["server"]
    volumes:
      - /srv/media/books/staging:/books
      - /srv/docker/openbooks/config:/config
    environment:
      - TZ=America/Toronto
