services:
  openbooks:
    image: evanbuss/openbooks:latest
    container_name: openbooks
    restart: unless-stopped
    ports:
      - "8083:5228"
    command:
      - server
      - --name 
      - whalesea
    volumes:
      - /srv/media/books/staging:/tmp/books
      - /srv/docker/openbooks/config:/config
    environment:
      - TZ=America/Toronto
