services:
  openbooks:
    image: evanbuss/openbooks:latest
    container_name: openbooks
    restart: unless-stopped
    ports:
      - "8083:80"
    command:
      - server
      - --name
      - whalesea
      - --dir
      - /books
      - --persist
      - --no-browser-downloads
    volumes:
      - /srv/media/books/staging:/books
    environment:
      - TZ=America/Toronto
